import type { CaseData } from "./types";
import { fmtFull } from "./dateFormatters";

export function generateMmrpNotification(data: CaseData): string {
  const lines: string[] = [];
  const ra = data.remedialAction;

  if (!ra) {
    return "ERROR: No remedial action data available for MMRP notification generation.";
  }

  const marineName = `${data.accusedRank} ${data.accusedLastName}, ${data.accusedFirstName}`;

  // Subject line
  lines.push("═══════════════════════════════════════════════════════════════");
  lines.push("                   MMRP SET-ASIDE NOTIFICATION");
  lines.push("═══════════════════════════════════════════════════════════════");
  lines.push("");
  lines.push(`Subject: MMRP SET-ASIDE NOTIFICATION - ${marineName} / ${data.accusedEdipi}`);
  lines.push("");

  // Marine identification
  lines.push("MARINE IDENTIFICATION:");
  lines.push(`  Name: ${data.accusedLastName}, ${data.accusedFirstName} ${data.accusedMiddleName}`.trim());
  lines.push(`  Rank/Grade: ${data.accusedRank} / ${data.accusedGrade}`);
  lines.push(`  EDIPI: ${data.accusedEdipi}`);
  lines.push(`  Unit: ${data.accusedUnit}`);
  lines.push(`  Component: ${data.component}`);
  lines.push("");

  // NJP info
  lines.push("NJP INFORMATION:");
  lines.push(`  Case Number: ${data.caseNumber}`);
  if (data.njpDate) {
    lines.push(`  NJP Date: ${fmtFull(data.njpDate)}`);
  }
  if (data.punishmentText) {
    lines.push(`  Original Punishment: ${data.punishmentText}`);
  }
  lines.push("");

  // Set-aside details
  lines.push("SET-ASIDE DETAILS:");
  lines.push(`  Action Type: ${ra.actionType.replace(/_/g, " ")}`);
  lines.push(`  Action Date: ${fmtFull(ra.actionDate)}`);
  lines.push(`  Authority: ${ra.actionAuthorityName}`);
  lines.push(`  Punishment Affected: ${ra.punishmentAffected}`);
  lines.push(`  Detail: ${ra.actionDetail}`);
  if (ra.reason) {
    lines.push(`  Reason: ${ra.reason}`);
  }
  if (ra.restorationLanguage) {
    lines.push("");
    lines.push("RESTORATION:");
    lines.push(`  ${ra.restorationLanguage}`);
  }
  lines.push("");

  // Commander action summary
  lines.push("COMMANDER ACTION SUMMARY:");
  lines.push(`  The above set-aside action has been taken on the NJP record of`);
  lines.push(`  ${marineName}. IPAC and MMRP should update records accordingly.`);
  lines.push("");

  lines.push("───────────────────────────────────────────────────────────────");
  lines.push("This notification was auto-generated by LegalFlow.");
  lines.push("═══════════════════════════════════════════════════════════════");

  return lines.join("\n");
}
